### PR TITLE
Backport 2 0 0

### PR DESCRIPTION
**Pull request by tiefling-cat**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tiefling-cat** [comment]
@conda-forge-admin, please rerender

**Comment by tiefling-cat** [comment]
@conda-forge/help-python please review at your convenience. The recipe is more or less identical to v 2.3.0

**Comment by tiefling-cat** [comment]
@dopplershift please review and approve or assign somebody who can, I understand that you all have other stuff to do, but I really need this approved ASAP to use it in my project.

**Comment by dopplershift** [comment]
When this feedstock was created, you should have received an invitation that invited you to join the organization and have permission to merge your own PRs on this repo. I'll push the bot to send you a new invite.

**Comment by dopplershift** [comment]
#2 should have caused you to receive a new invite. Please look for it (check spam) and accept and you'll be good to handle this on your own!

**Comment by tiefling-cat** [comment]
> #2 should have caused you to receive a new invite. Please look for it (check spam) and accept and you'll be good to handle this on your own!

Yes, I got it and joined, thank you very much! I didn't notice it the first time, because my github email address is not my primary mailbox.

**Pull request merged**
